### PR TITLE
fixes #155 Incorrect ordering in moderation page

### LINKED ISSUE #155: Incorrect ordering in moderation page
Expected ordering is to display not moderated posts first and then display the rest from the latest (no matter if they are rejected or approved).

Currently ordering is as follows:
1. Not moderated posts (approved = null)
2. Rejected posts (approved = false) from the lasest
3. Accepted posts (approved = true) from the lastest

As a result latest approved posts are at ~17 page in data table.

### PR DESCRIPTION
**Pull request by mszarlinski**

### CODE REVIEW

File: src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+            approved | expectedState
+            true     | "Approved"
+            false    | "Rejected"
+            null     | " -- "
+    }
+
+    @Unroll
+    def "Should return #expected when isModerated called for post with approved = #approved"(final Boolean approved, final boolean expected) {
+        given:
+            def blogPost = new BlogPost(approved: approved)
```
Comment (tdziurko) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy]: Please avoid "def"s, for a consistenty we try to use stati types where possible.

File: src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    @Unroll
+    def "Should return #expected when isModerated called for post with approved = #approved"(final Boolean approved, final boolean expected) {
+        given:
+            final BlogPost blogPost = new BlogPost(approved: approved)
+        when:
+            final boolean isModerated = blogPost.isModerated()
+        then:
+            isModerated == expected
+        where:
+            approved | expected
```
Comment (tdziurko) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy]: Inputs and expected outputs can be separated with a double pipe symbol (||) to visually set them apart.

File: src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+            true     | true
+            false    | true
+            null     | false
+    }
+
+    @Unroll
+    def "Should return #expected when isNotModerated called for post with approved = #approved"(final Boolean approved, final boolean expected) {
+        given:
+            final BlogPost  blogPost = new BlogPost(approved: approved)
```
Comment (tdziurko) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy]: Not sure about those finals here :) But this is a topic for a discussion.

Comment (goostleek) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy]: My approach is to always mark declared class fields and local variables final (where possible) to avoid accidental reference overwriting. I have even save action on that (marking all possible variables final except parameters). Lombok has even a support for that (see [`val`](https://projectlombok.org/features/val.html) keyword).

File: src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostRepositorySpec.groovy [hunk 4]
```diff
@@ -39,24 +38,28 @@ class BlogPostRepositorySpec extends SpringContextAwareSpecification {
...
+            latestPosts[2].getPublishedDate().isAfter(latestPosts[3].getPublishedDate())
+            latestPosts[3].getPublishedDate().isAfter(latestPosts[4].getPublishedDate())
             latestPosts[4].getPublishedDate().isAfter(latestPosts[5].getPublishedDate())
     }
 
     private Blog aBlog() {
-        def blog = new Blog(jsonId: 1L, author: "Top Blogger", rss: "http://topblogger.pl/", dateAdded: LocalDateTime.now(), blogType: PERSONAL)
-        return blogRepository.save(blog)
+        return blogRepository.save(
+                new Blog(jsonId: 1L, author: "Top Blogger", rss: "http://topblogger.pl/",
```
Comment (goostleek) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostRepositorySpec.groovy]: Try to avoid _GroovyBeans_ provided constructors and prefer `Blog.builder()` instead. _GroovyBeans_ style constructors are error prone because if the field name is changed then you will get feedback late at runtime. Using builder you will benefit from IDE code completion and errors will be highlighted instantaneously when test is broken by subject code changes.

File: src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPost.java [hunk 5]
```diff
@@ -70,6 +70,10 @@ public boolean isRejected() {
         return Boolean.FALSE.equals(approved);
     }
 
+    public boolean isModerated() {
+        return approved != null;
+    }
+
     public boolean isNotModerated() {
```
Comment (goostleek) [inline src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPost.java]: I think after introducing `isModerated()` we don't need ~~`isNotModerated()`~~ method anymore as its occurences  can be replaced by  `!isModerated()`. Refactoring will be easy because it's used only in [`BlogPostRepositorySpec`](https://github.com/tdziurko/jvm-bloggers/pull/156/files#diff-97cee16ec747fb35c69c3be009e7366dR44).

File: src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy (hunk 3 above)
Comment (mszarlinski) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy]: I totally agree when it comes to production code. We all know that using "final" keyword there improves reasoning about the code. It is even more important, because production methods are likely to grow (that's why we refactor after some time). On the other hand, test methods have always much smaller flow than production ones and using "final" is a subject for discussion, as @tdziurko wrote. I agree with him using "final", "final" and "final" everywhere in tests make too much noise and there is too little gain from it.

Comment (goostleek) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blog_posts/domain/BlogPostSpec.groovy]: Ok, that's reasonable, you convinced me to have tests free from final.
