### PR TITLE
[#175] Handling invalid URLs in BloggersDataFetcher.

### LINKED ISSUE #175: BloggersDataFetcher is not handling invalid URL correctly
`BloggersDataFetcher` is calling `Optional::get` even on empty `Optional` causing `NoSuchElementException`

Also there are no tests for main responsibilities of this class: reading and parsing jsons files.

### PR DESCRIPTION
**Pull request by airborn**
Fixes #175

### CODE REVIEW

File: src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcher.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
     private final Optional<URL> bloggersUrlOptional;
     private final Optional<URL> companiesUrlOptional;
     private final BloggersDataUpdater bloggersDataUpdater;
+    private final ObjectMapper mapper = new ObjectMapper();
```
Comment (goostleek) [inline src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcher.java]: Why did you move the `mapper` to global scope if it's only used in the `refreshBloggersDataFor`(https://github.com/tdziurko/jvm-bloggers/pull/176/files#diff-492313bd8196a0a1a2ae2b2e32a15e5cL55) scope?

Comment (airborn) [inline src/main/java/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcher.java]: Because `refreshBloggersDataFor` is called multiple times, and there is no need to create multiple instances of `ObjectMapper` which is a heavy weight object.

File: src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcherSpec.groovy [hunk 2]
```diff
@@ -4,28 +4,28 @@ import spock.lang.Specification
 
 class BloggersDataFetcherSpec extends Specification {
 
-    def "Should store empty optional when url is not valid"() {
+    def "Should not throw exception during fetching when url is not valid"() {
```
Comment (goostleek) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcherSpec.groovy]: We've got to test cases here:

* _Should not throw exception during fetching when url is not valid_
* _Should update bloggers data from valid url_

The first one contains _during fetching_ which is nit necessary I think. If you remove it the test cases will better match to each other IMHO:

* _Should not throw exception when url is not valid_
* _Should update bloggers data from valid url_

WDYT?

Comment (airborn) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcherSpec.groovy]: Fair point

File: src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcherSpec.groovy [hunk 3]
```diff
@@ -4,28 +4,28 @@ import spock.lang.Specification
...
-            !fetcher.companiesUrlOptional.isPresent()
+            notThrown Exception
     }
 
-    def "Should store valid URL with valid input"() {
+    def "Should update bloggers data from valid url"() {
         given:
-            String urlString = "http://google.com"
-            String urlString2 = "http://facebook.com"
+            String urlString = getClass().getResource("bloggers.json").toExternalForm()
```
Comment (tdziurko) [inline src/test/groovy/pl/tomaszdziurko/jvm_bloggers/blogs/BloggersDataFetcherSpec.groovy]: maybe test_bloggers.json and test_companies.json to avoid accidental mistakes with production files?
